/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {CircleHelp,RefreshCw,Search} from "lucide-react";
import {AppShell} from "@/components/app-shell";
import {EmptyState,Section} from "@/components/ui";
import {DiscoveryTarget,getDiscoveryTargets,runDiscoveryNow} from "@/lib/api";
import {environmentBadge} from "@/lib/environment";

const yen=(value:number)=>new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(value);
const categories=["すべて","iPhone","iPad","AirPods","Apple Watch","PlayStation","Nintendo Switch","その他"] as const;
const states=[{key:"all",label:"すべて"},{key:"unsearched",label:"未検索"},{key:"failed",label:"検索失敗"},{key:"found",label:"販売商品あり"},{key:"profitable",label:"利益あり"},{key:"near",label:"BUYに近い"},{key:"multi",label:"複数買取店"}] as const;
type StateKey=(typeof states)[number]["key"];
type SortKey="priority"|"gap"|"buyback"|"updated";
function family(item:DiscoveryTarget){const value=`${item.productName} ${item.category??""}`.toLowerCase();if(value.includes("iphone"))return "iPhone";if(value.includes("ipad"))return "iPad";if(value.includes("airpods"))return "AirPods";if(value.includes("apple watch"))return "Apple Watch";if(value.includes("playstation")||value.includes("ps5")||value.includes("ps4"))return "PlayStation";if(value.includes("switch"))return "Nintendo Switch";return "その他"}
function providerLabel(value:string){return value==="kaitori_1chome"?"買取1丁目":value==="morimori"?"森森買取":value==="kaitori_shouten"?"買取商店":value}
function stateLabel(state:{status:string;lastSearchedAt:string|null;failureCount:number}){if(state.status==="failed")return `検索失敗（${state.failureCount}回）`;if(state.lastSearchedAt)return state.status==="succeeded"?"検索済み":"検索中";return "検索待ち"}
function matchesState(item:DiscoveryTarget,key:StateKey,providers:string[]){const providerStates=providers.map(name=>name==="amazon"?item.amazon:name==="rakuten"?item.rakuten:item.yahoo);if(key==="unsearched")return providerStates.every(value=>!value.lastSearchedAt);if(key==="failed")return providerStates.some(value=>value.status==="failed");if(key==="found")return item.retailResultCount>0;if(key==="profitable")return (item.estimatedProfit??0)>0;if(key==="near")return item.profitGap!==null&&item.profitGap>0&&item.profitGap<=3000;if(key==="multi")return item.buybackProviderCount>1;return true}
function statusTone(state:{status:string;lastSearchedAt:string|null}){return state.status==="failed"?"blocked":state.lastSearchedAt?"active":"ready"}
function ProviderState({value}:{value:DiscoveryTarget["yahoo"]}){return <div><span className={`status-pill ${statusTone(value)}`}>{stateLabel(value)}</span><small>{value.lastSearchedAt?new Date(value.lastSearchedAt).toLocaleString("ja-JP"):"自動で順次検索"}</small>{value.lastSearchedAt&&<small>{value.resultCount?`${value.resultCount}件発見`:"該当商品なし"}</small>}</div>}
const enabledStates=(item:DiscoveryTarget,providers:string[])=>providers.map(name=>name==="amazon"?item.amazon:name==="rakuten"?item.rakuten:item.yahoo);

export default function TargetsPage(){
 const[items,setItems]=useState<DiscoveryTarget[]>([]),[providers,setProviders]=useState<string[]>(["yahoo","rakuten"]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[exploring,setExploring]=useState(false),[lastUpdated,setLastUpdated]=useState<Date|null>(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[category,setCategory]=useState<(typeof categories)[number]>("すべて"),[state,setState]=useState<StateKey>("all"),[sort,setSort]=useState<SortKey>("priority");
 const load=useCallback(async(background=false)=>{if(!background)setLoading(true);setError("");try{const data=await getDiscoveryTargets();setItems(Array.isArray(data.items)?data.items:[]);setProviders(Array.isArray(data.providers)&&data.providers.length?data.providers:["yahoo","rakuten"]);setTotal(data.total);setLastUpdated(new Date())}catch(e){setError(e instanceof Error?e.message:"探索対象商品を取得できませんでした")}finally{if(!background)setLoading(false)}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),30_000);return()=>window.clearInterval(timer)},[load]);
 const categoryCounts=useMemo(()=>Object.fromEntries(categories.map(name=>[name,name==="すべて"?items.length:items.filter(item=>family(item)===name).length])),[items]);
 const stateCounts=useMemo(()=>Object.fromEntries(states.map(option=>[option.key,items.filter(item=>matchesState(item,option.key,providers)).length])),[items,providers]);
 const filtered=useMemo(()=>{const needle=query.trim().toLowerCase(),result=items.filter(item=>(category==="すべて"||family(item)===category)&&matchesState(item,state,providers)&&(!needle||[item.productName,item.jan,item.modelNumber,item.searchQuery,item.bestBuybackProvider].some(value=>String(value??"").toLowerCase().includes(needle))));return result.sort((a,b)=>sort==="gap"?(a.profitGap??Number.MAX_SAFE_INTEGER)-(b.profitGap??Number.MAX_SAFE_INTEGER):sort==="buyback"?b.bestBuybackPrice-a.bestBuybackPrice:sort==="updated"?Date.parse(b.latestResultAt??"1970-01-01")-Date.parse(a.latestResultAt??"1970-01-01"):enabledStates(b,providers).filter(value=>!value.lastSearchedAt).length-enabledStates(a,providers).filter(value=>!value.lastSearchedAt).length||b.bestBuybackPrice-a.bestBuybackPrice)},[items,query,category,state,sort,providers]);
 const providerSearches=items.reduce((sum,item)=>sum+enabledStates(item,providers).filter(value=>value.lastSearchedAt).length,0),providerTotal=items.length*providers.length,progress=providerTotal?providerSearches/providerTotal*100:0,remaining=Math.max(providerTotal-providerSearches,0),remainingMinutes=Math.ceil(remaining/20)*15,remainingLabel=remaining===0?"完了":remainingMinutes<60?`約${remainingMinutes}分`:`約${Math.ceil(remainingMinutes/60)}時間`,providerProgress=providers.map(name=>({name,label:name==="yahoo"?"Yahoo!":name==="rakuten"?"楽天":"Amazon",searched:items.filter(item=>(name==="amazon"?item.amazon:name==="rakuten"?item.rakuten:item.yahoo).lastSearchedAt).length,failed:items.filter(item=>(name==="amazon"?item.amazon:name==="rakuten"?item.rakuten:item.yahoo).status==="failed").length})),fullySearched=items.filter(item=>enabledStates(item,providers).every(value=>value.lastSearchedAt)).length,found=items.filter(item=>item.retailResultCount>0).length,failed=items.filter(item=>enabledStates(item,providers).some(value=>value.status==="failed")).length,amazonEnabled=providers.includes("amazon");
 const explore=async()=>{setExploring(true);setError("");try{await runDiscoveryNow();await load(true)}catch(e){setError(e instanceof Error?e.message:"探索を開始できませんでした")}finally{setExploring(false)}};
 return <AppShell title="探索対象商品" description="買取価格を起点に、販売サイトで安い商品を探しています。" badge={environmentBadge} actions={<><Link className="tool-button" href="/guide#targets"><CircleHelp/>見方</Link><button className="tool-button primary" onClick={()=>void explore()} disabled={exploring}><Search/>{exploring?"探索中…":"今すぐ探索"}</button><button className="tool-button" onClick={()=>void load()} disabled={loading}><RefreshCw/>更新</button></>}>
  <section className="target-summary"><div className="target-progress"><div><span>販売サイト探索の進捗</span><b>{providerSearches.toLocaleString("ja-JP")} / {providerTotal.toLocaleString("ja-JP")}回</b><small>全{total.toLocaleString("ja-JP")}商品を{providers.map(name=>name==="yahoo"?"Yahoo!":name==="rakuten"?"楽天":"Amazon").join("・")}でそれぞれ探索します</small><small>30秒ごとに自動更新{lastUpdated?` ・ 最終更新 ${lastUpdated.toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}`:""}</small></div><div className="progress-side"><strong>{progress.toFixed(1)}%</strong><small>残り {remainingLabel}</small></div><div className="progress-track"><i style={{width:`${Math.min(progress,100)}%`}}/></div><div className="provider-progress-list">{providerProgress.map(value=><div key={value.name}><span>{value.label}</span><b>{value.searched.toLocaleString("ja-JP")} / {items.length.toLocaleString("ja-JP")}</b><small>{value.failed?`失敗 ${value.failed}件・自動再試行`:"正常"}</small></div>)}</div></div><div className="target-summary-cards"><article><small>全サイト検索済み</small><b>{fullySearched.toLocaleString("ja-JP")}</b><span>商品</span></article><article><small>販売商品あり</small><b>{found.toLocaleString("ja-JP")}</b><span>商品</span></article><article><small>検索失敗</small><b className={failed?"danger":""}>{failed.toLocaleString("ja-JP")}</b><span>商品</span></article><article><small>利益あり</small><b className="positive">{Number(stateCounts.profitable??0).toLocaleString("ja-JP")}</b><span>商品</span></article></div></section>
  {error&&<div className="notice error" role="alert">{error}<button onClick={()=>void load()}>再試行</button></div>}
  <Section title="商品一覧" description="未検索・検索済み0件・商品発見を区別して表示します。JANや容量・色が違う商品は別々に管理します。">
   <div className="target-controls"><div className="target-control-row"><label className="search-field"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="商品名・JAN・型番・買取店で検索"/></label><label className="target-sort">並び順<select value={sort} onChange={event=>setSort(event.target.value as SortKey)}><option value="priority">未検索を優先</option><option value="gap">BUYまで近い順</option><option value="buyback">最高買取価格順</option><option value="updated">販売価格の更新順</option></select></label></div><div className="target-filter-group"><b>状態</b><div className="target-tabs">{states.map(option=><button key={option.key} className={state===option.key?"selected":""} onClick={()=>setState(option.key)}>{option.label}<b>{Number(stateCounts[option.key]??0).toLocaleString("ja-JP")}</b></button>)}</div></div><div className="target-filter-group"><b>カテゴリ</b><div className="target-tabs">{categories.map(name=><button key={name} className={category===name?"selected":""} onClick={()=>setCategory(name)}>{name}<b>{Number(categoryCounts[name]??0).toLocaleString("ja-JP")}</b></button>)}</div></div></div>
   {loading?<div className="table-message">探索状況を読み込んでいます…</div>:filtered.length?<div className={`target-table${amazonEnabled?" amazon-enabled":""}`}><div className="target-head"><span>商品</span><span>買取</span><span>販売・利益</span><span>Yahoo!</span><span>楽天</span>{amazonEnabled&&<span>Amazon</span>}</div>{filtered.map(item=>{const gapTone=item.profitGap===0?"buy":item.profitGap!==null&&item.profitGap<=3000?"ready":"blocked";return <article className="target-row clearer" key={item.id}><div className="target-product"><div><span className="target-family">{family(item)}</span>{item.buybackProviderCount>1&&<span className="target-family multi">{item.buybackProviderCount}店舗比較</span>}</div><b>{item.productName}</b><small>JAN {item.jan||"未取得"} ・ 型番 {item.modelNumber||"未取得"}</small><small>検索語: {item.searchQuery}</small></div><div><small>最高買取</small><strong>{yen(item.bestBuybackPrice)}</strong><small>{providerLabel(item.bestBuybackProvider)}</small><small>仕入目標 {yen(item.targetPurchasePrice)}</small></div><div>{item.lowestRetailPrice===null?<><small>販売価格</small><strong>未発見</strong><small>{item.retailResultCount?"価格を確認できません":"検索後に表示します"}</small></>:<><small>販売最安</small><strong>{yen(item.lowestRetailPrice)}</strong><span className={`status-pill ${gapTone}`}>{item.profitGap===0?`利益 ${yen(item.estimatedProfit??0)}`:`BUYまであと ${yen(item.profitGap??0)}`}</span><small>{item.retailResultCount}件・{item.retailProviderCount}サイト</small></>}</div><ProviderState value={item.yahoo}/><ProviderState value={item.rakuten}/>{amazonEnabled&&<ProviderState value={item.amazon}/>}</article>})}</div>:<EmptyState>条件に一致する探索対象商品はありません。絞り込み条件を変更してください。</EmptyState>}
   {!loading&&<div className="table-footer">{filtered.length.toLocaleString("ja-JP")}件を表示</div>}
  </Section>
 </AppShell>
}
