/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {useCallback,useEffect,useState} from "react";
import {RefreshCw} from "lucide-react";
import {AppShell} from "@/components/app-shell";
import {getResearchSettings,ResearchSettings,saveResearchSettingsData} from "@/lib/api";
import {environmentBadge} from "@/lib/environment";
const initial:ResearchSettings={initialCapital:300000,minimumProfit:5000,minimumConfidence:.95,saleShipping:1000,fees:0,evaluationHours:[24,48,72,168]};
export default function SettingsPage(){const[x,setX]=useState(initial),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);setError("");try{setX(await getResearchSettings())}catch(e){setError(e instanceof Error?e.message:"設定を取得できませんでした")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const number=(key:keyof ResearchSettings)=>(e:React.ChangeEvent<HTMLInputElement>)=>setX({...x,[key]:Number(e.target.value)});const save=async()=>{setNotice("");setError("");if(x.initialCapital<=0||x.minimumProfit<0||x.minimumConfidence<.5||x.minimumConfidence>1||x.saleShipping<0||x.fees<0){setError("入力値を確認してください。信頼度は0.5〜1、金額は0以上です。");return}if(!x.evaluationHours.length){setError("評価時間を1つ以上選択してください。");return}setSaving(true);try{setX(await saveResearchSettingsData(x));setNotice("設定を保存しました。次回の判定から反映されます。")}catch(e){setError(e instanceof Error?e.message:"設定を保存できませんでした")}finally{setSaving(false)}};return <AppShell capital={x.initialCapital} title="研究設定" description="保存した値は次回の判定・Paper Tradingから使用されます。" badge={environmentBadge} actions={<button className="tool-button" onClick={()=>void load()} disabled={loading}><RefreshCw/>再読込</button>}>
{error&&<div className="notice error" role="alert">{error}</div>}{notice&&<div className="notice success" role="status">{notice}</div>}{loading?<div className="table-message">設定を読み込んでいます</div>:<section className="settings-layout"><div className="settings-card"><h2>判定・資金設定</h2><label><span>初期資金<small>Paper Trading上限</small></span><input type="number" min="1" value={x.initialCapital} onChange={number("initialCapital")}/></label><label><span>最低利益<small>48時間後も残したいMarket Profit</small></span><input type="number" min="0" value={x.minimumProfit} onChange={number("minimumProfit")}/></label><label><span>最低信頼度<small>0.50〜1.00</small></span><input type="number" min="0.5" max="1" step="0.01" value={x.minimumConfidence} onChange={number("minimumConfidence")}/></label><label><span>売却送料</span><input type="number" min="0" value={x.saleShipping} onChange={number("saleShipping")}/></label><label><span>手数料</span><input type="number" min="0" value={x.fees} onChange={number("fees")}/></label><button className="save-button" onClick={()=>void save()} disabled={saving}>{saving?"保存中…":"設定を保存"}</button></div><div className="settings-card"><h2>評価時間</h2>{[24,48,72,168].map(h=><label key={h}><span>{h===168?"7日":`${h}時間`}後</span><input type="checkbox" checked={x.evaluationHours.includes(h)} onChange={e=>setX({...x,evaluationHours:e.target.checked?[...x.evaluationHours,h].sort((a,b)=>a-b):x.evaluationHours.filter(v=>v!==h)})}/></label>)}<h2 className="guard-title">環境ガード</h2>{["本番でのモック利用","CAPTCHA・ログイン回避","価格履歴の上書き"].map(v=><div className="guard-row" key={v}><span>{v}</span><b className="off">禁止</b></div>)}</div></section>}</AppShell>}
