import Link from "next/link";
import {AppShell} from "@/components/app-shell";
import {environmentBadge} from "@/lib/environment";

const pages=[
 {id:"research",name:"案件リサーチ",href:"/",purpose:"Sprea全体の現在地と、利益案件がどこで消えているかを確認するホーム画面です。",items:["上段には該当商品数、利用可能資金、拘束中資金、48時間評価のPrecision、検出利益合計が表示されます。","商品探索ファネルは、買取Quoteから候補化、Canonical Product化、販売サイト発見、新品・在庫確認、利益あり、5,000円以上、BUYまでの件数を左から順に示します。","販売サイト別の探索結果ではYahoo!と楽天の検索件数、失敗数、商品一致数、Listing数、利益候補数、平均不足額を比較します。","本日の判定分析はJSTの0:00〜23:59が対象です。SKIP理由は複数付くため、理由別件数の合計はSKIP総数と一致しない場合があります。","『あと』は必要利益から現在利益を引いた不足額です。BUY条件を満たす場合は0円で、マイナスにはなりません。"]},
 {id:"targets",name:"探索対象商品",href:"/targets",purpose:"買取店に存在する商品を起点に、Yahoo!・楽天で安い販売商品を探す対象一覧です。",items:["上部の進捗は、全商品をYahoo!・楽天で1回ずつ検索するための総回数に対する完了率です。『両方検索済み』は2サイトとも検索を終えた商品数です。","同じ機種名でもJAN、容量、色、Editionが違えば別商品です。iPhoneが多く見えるのは、この安全なバリエーション分離によるものです。","状態ボタンで未検索、検索失敗、販売商品あり、利益あり、BUYに近い、複数買取店ありに絞り込めます。BUYに近いは利益条件まで3,000円以内の商品です。","カテゴリボタンと検索欄を組み合わせ、商品名、JAN、型番、検索語、最高買取Providerを横断検索できます。","並び順は未検索優先、BUYまで近い順、最高買取価格順、販売価格の更新順から選べます。","最高買取は現在把握している買取店の最高額です。販売最安との差から概算利益と『BUYまであと』を表示します。最終BUY判定では送料・手数料・鮮度なども改めて確認します。","Yahoo!・楽天は検索待ち、検索済み、検索失敗として別々に管理されます。検索済みで販売商品0件の場合は『該当商品なし』と表示され、未検索とは区別されます。"]},
 {id:"opportunities",name:"該当商品",href:"/opportunities",purpose:"販売価格と買取価格の組み合わせから作られた、具体的な利益候補を確認します。",items:["同じCanonical Productについて、購入可能でFreshな販売Listingと、受付中でFreshな買取Quoteが揃った場合だけ候補になります。","販売側は新品、在庫ありまたは残りわずか、価格が正、URLが有効、取得後120分以内である必要があります。","買取側は新品系、受付中、価格が正、商品解決済み、取得後180分以内である必要があります。","複数の販売Listingでは、商品価格＋送料−確実な還元で計算した実質仕入価格が最も安いものを選びます。","複数の買取QuoteではProviderごとの最新値だけを使い、上位3店舗と最高額・2位との差を保持します。","Market Profitは、最高買取価格−売却送料−売却手数料−購入価格−購入送料＋確実な還元です。クーポンなど確実でない値は含めません。","商品名を押すと商品詳細へ移動し、価格履歴と判定履歴を確認できます。"]},
 {id:"paper",name:"Paper Trading",href:"/paper-trading",purpose:"実際に購入せず、BUY案件を仮想資金で購入した場合の資金と保有状況を追跡します。",items:["初期資金は現在30万円です。1商品につき1個、同じCanonical Productの重複保有は禁止です。","BUY判定でも資金不足や同一商品保有中の場合は約定せず、その拒否理由が判定分析へ戻されます。","利用可能資金は新規購入に使える金額、拘束資金は保有中の仮想仕入額です。","保有には商品、仕入先、買取先、購入価格、想定買取価格、期待利益、開始日時が記録されます。","Paper Tradingは実注文・実決済を一切行いません。表示だけを根拠に実購入しないでください。"]},
 {id:"evaluations",name:"自動評価",href:"/evaluations",purpose:"Opportunity生成後の価格を追跡し、当時のBUY／SKIPが正しかったかを検証します。",items:["24時間、48時間、72時間、7日後のチェックポイントを持ちます。評価時刻になっても必要な価格データがなければ、データ待ちになります。","BUY後も必要利益を維持したか、BUYが失敗したか、SKIPした商品が後から利益案件になったかを記録します。","Opportunity Decayは生成時から評価時点までに利益がどれだけ減ったかを示します。","48h PrecisionはBUYした案件のうち48時間後も成功条件を満たした割合です。件数が少ない段階では参考値として扱います。","手動評価は評価期限が来たデータだけを処理し、未来の評価結果を先取りしません。"]},
 {id:"sources",name:"データ取得元",href:"/sources",purpose:"販売サイト・買取店ごとの接続状態と、Collectorの実行履歴を確認します。",items:["販売側はYahoo!ショッピング、楽天市場、Amazon.co.jpの公式APIに対応します。AmazonはCreators APIの認証情報を設定した場合だけ探索対象になります。Webページはスクレイピングしません。","買取側は買取1丁目、森森買取、買取商店のPublic Collectorから取り込みます。","接続済みは実データの取得履歴がある状態、設定済みは認証情報はあるがまだデータがない状態です。","件数と最終成功日時が更新されているかを確認してください。0件取得や長時間更新されない状態はHTML変更やAPI障害の可能性があります。","1つのProviderが失敗しても、他Providerの取得は継続する設計です。実行履歴のメッセージで失敗元を確認できます。","イオシスとApple.comは現在の通常取得対象ではありません。禁止・未接続表示は故障を意味しません。"]},
 {id:"settings",name:"設定",href:"/settings",purpose:"利益判定、商品同定、Paper Trading、評価に使う基準を確認・変更します。",items:["最低利益は現在5,000円、最低Confidenceは0.95です。検証のために安易に緩めない運用です。","売却送料と手数料はMarket Profitから差し引かれ、次回生成されるOpportunityから反映されます。既存Opportunityの当時値は書き換えません。","評価時間は24時間、48時間、72時間、168時間です。","本番Mock、CAPTCHA・ログイン回避、価格履歴の上書きは禁止されています。","設定保存前に値の意味を確認してください。利益閾値の変更はBUY件数だけでなく評価データの比較可能性にも影響します。"]},
 {id:"product",name:"商品詳細",href:"/products",purpose:"1つのCanonical Productについて、同定情報・価格履歴・判定・評価を時系列で確認します。",items:["商品詳細は一覧の商品リンクから開きます。URLだけで開く場合は商品キーの指定が必要です。","JAN、型番、容量、色など、別サイトの商品を同一商品と判断した根拠を確認できます。","販売価格と買取価格の履歴は別系列です。取得時刻とProviderを見て、古い価格を現在価格と誤認しないでください。","ConfidenceとmatchReasonは商品同定の確からしさと根拠です。JAN完全一致が最優先で、型番、型番＋属性、商品名＋属性の順に判定します。"]}
];

export default function GuidePage(){return <AppShell title="使い方" description="Spreaの画面、数字、判定条件、日常運用を詳しく説明します。" badge={environmentBadge}>
 <div className="guide-layout"><aside className="guide-toc"><b>目次</b><a href="#start">最初にすること</a>{pages.map(page=><a href={`#${page.id}`} key={page.id}>{page.name}</a>)}<a href="#terms">用語と判定</a><a href="#operation">日常運用</a><a href="#trouble">困ったとき</a><a href="#maintenance">仕様更新</a></aside><div className="guide-content">
  <section className="guide-intro"><span>USER GUIDE</span><h1>Spreaを安全に使うためのガイド</h1><p>Spreaは、買取店の価格から商品候補を作り、販売サイトで安く買える新品を探し、利益と商品一致精度を判定するリサーチシステムです。実際の注文や支払いは行いません。</p><div><b>現在の重要基準</b><ul><li>最低Market Profit：5,000円</li><li>最低商品一致Confidence：0.95</li><li>販売価格の有効期間：120分</li><li>買取価格の有効期間：180分</li><li>Paper Trading初期資金：300,000円</li></ul></div></section>
  <section className="guide-section" id="start"><h2>最初にすること</h2><ol><li><Link href="/sources">データ取得元</Link>で販売・買取Providerが接続済みか確認します。</li><li><Link href="/targets">探索対象商品</Link>で対象数とYahoo!・楽天の検索進捗を確認します。</li><li><Link href="/">案件リサーチ</Link>で探索ファネルとSKIP理由を確認します。</li><li>利益5,000円以上の候補が出たら<Link href="/opportunities">該当商品</Link>で価格、在庫、店舗数、更新時刻を確認します。</li><li><Link href="/paper-trading">Paper Trading</Link>と<Link href="/evaluations">自動評価</Link>で、実購入せずに成績を蓄積します。</li></ol><div className="guide-flow"><span>買取価格取得</span><i>→</i><span>商品統合</span><i>→</i><span>販売商品探索</span><i>→</i><span>利益判定</span><i>→</i><span>仮想売買</span><i>→</i><span>将来評価</span></div></section>
  {pages.map(page=><section className="guide-section" id={page.id} key={page.id}><div className="guide-heading"><div><small>PAGE GUIDE</small><h2>{page.name}</h2></div><Link className="tool-button" href={page.href}>ページを開く</Link></div><p>{page.purpose}</p><ul>{page.items.map(item=><li key={item}>{item}</li>)}</ul></section>)}
  <section className="guide-section" id="terms"><h2>用語と判定の意味</h2><dl className="guide-terms"><div><dt>Buyback Quote</dt><dd>買取店が提示している商品、価格、受付状態、取得時刻の記録です。</dd></div><div><dt>Product Candidate</dt><dd>複数の買取QuoteからJAN・型番などで重複を整理した探索候補です。</dd></div><div><dt>Canonical Product</dt><dd>販売サイトと買取店を横断して同一商品を結びつけるSprea内部の基準商品です。</dd></div><div><dt>Retail Listing</dt><dd>Yahoo!や楽天で購入できる販売商品の価格、送料、在庫、URLの記録です。</dd></div><div><dt>Opportunity</dt><dd>同一Canonical Productの販売Listingと買取Quoteを組み合わせ、利益を計算した案件です。</dd></div><div><dt>Confidence</dt><dd>商品同定の確からしさです。JAN完全一致は1.00、型番完全一致は0.99を基本とします。</dd></div><div><dt>BUY / SKIP</dt><dd>BUYは利益・Confidence・鮮度・在庫などをすべて満たす候補、SKIPはいずれかを満たさない候補です。</dd></div><div><dt>Sprea Score</dt><dd>利益、商品同定、買取店数、価格差、鮮度などから案件の研究優先度を表す評価値です。利益の保証ではありません。</dd></div><div><dt>Fresh / stale</dt><dd>定めた有効時間内の価格がFresh、期限を過ぎた価格がstaleです。stale価格はOpportunityに使いません。</dd></div></dl></section>
  <section className="guide-section" id="operation"><h2>日常運用のおすすめ</h2><h3>毎日</h3><ul><li>データ取得元で最終成功時刻と0件異常を確認する。</li><li>案件リサーチでBUY件数、SKIP理由、平均利益不足額を確認する。</li><li>該当商品があれば、価格取得時刻・在庫・商品バリエーションを再確認する。</li></ul><h3>週1回</h3><ul><li>探索対象商品の未検索・失敗が減っているか確認する。</li><li>48時間・72時間・7日評価の件数と価格維持率を確認する。</li><li>Provider別の失敗増加や平均利益不足額の変化を比較する。</li></ul><h3>変更しないもの</h3><p>BUYが出ないという理由だけで最低利益5,000円やConfidence 0.95を下げません。まず、商品母数、販売価格、送料、買取価格、検索精度のどこが原因かをファネルとSKIP理由で確認します。</p></section>
  <section className="guide-section" id="trouble"><h2>困ったとき</h2><dl className="guide-faq"><div><dt>数字が0件です</dt><dd>未検索なのか、検索済みで未発見なのかを探索対象商品で確認し、次にデータ取得元の最終成功時刻を確認してください。</dd></div><div><dt>iPhoneが200件以上あります</dt><dd>同じシリーズでも容量・色・JANが異なるためです。安全な商品同定のため別候補として扱います。</dd></div><div><dt>BUYがありません</dt><dd>本日の判定分析で利益不足、Confidence不足、買取店舗不足、資金不足などを確認します。平均不足額が大きければ閾値より仕入価格側が主因です。</dd></div><div><dt>Yahoo!だけ検索済みです</dt><dd>Providerごとのキューは独立しています。楽天は別の順番で検索されます。</dd></div><div><dt>販売商品を発見したのにOpportunityがありません</dt><dd>中古、在庫なし、価格が古い、商品属性不一致、利益不足、買取停止などで除外された可能性があります。</dd></div><div><dt>画面が更新されません</dt><dd>画面の更新ボタンを押し、データ取得元とAPIの状態を確認してください。ブラウザの再読み込みだけでは新しい収集処理は開始しません。</dd></div></dl></section>
  <section className="guide-section guide-maintenance" id="maintenance"><h2>仕様変更時の更新方針</h2><p>このガイドは製品仕様の一部として管理します。画面、項目名、判定式、閾値、Provider、Freshness、定期処理が変わる変更では、同じPull Request内でこのページも更新する運用です。</p><p>ページ下部の更新日が古い場合は、実画面と設定画面の値を優先してください。</p><small>最終更新：2026年8月30日（Amazon Creators API Collector対応）</small></section>
 </div></div>
 </AppShell>}
